package edu.psu.jjb24.csjokes.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="users")
public class User {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public User(int userID, String phoneNumber, String userName, boolean preferedContact) {
        this.userID = userID;
        this.phoneNumber = phoneNumber;
        this.userName = userName;
        this.preferedContact = preferedContact;

    }

    // Assign 0 to id to have it be auto generated
    /*@PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rowid")
    public int id;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "setup")
    public String setup;

    @ColumnInfo(name = "punchline")
    public String punchline;

    @ColumnInfo(name = "liked")
    public boolean liked;*/

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "userID")
    public int userID;

    @ColumnInfo(name = "phoneNumber")
    public String phoneNumber;

    @ColumnInfo(name = "userName")
    public String userName;

    @ColumnInfo(name = "preferedContact")
    public boolean preferedContact;
}
